crop_thresh: 0.5
attr_thresh: 0.5
kpt_thresh: 0.2
visual: True
warmup_frame: 50

DET:
  model_dir: detector/model_dir/crowdhuman_yolov5m.pt
  batch_size: 1

ATTR:
  model_dir: output_inference/strongbaseline_r50_30e_pa100k/
  batch_size: 8

MOT:
  model_dir: deep_sort/configs/osnet_x0_25_msmt17.pth
  tracker_config: deep_sort/configs/deep_sort.yaml

KPT:
  model_dir: output_inference/dark_hrnet_w32_256x192/
  batch_size: 8

ACTION:
  model_dir: output_inference/STGCN
  batch_size: 1
  max_frames: 50
  display_frames: 80
  coord_size: [384, 512]

REID:
  model_dir: output_inference/reid_model/
  batch_size: 16